### ISSUE TITLE
 Liquid Exception: Liquid syntax error (line 1): Unknown tag 'swagger'

### ISSUE THREAD

**Issue by shubhank-saxena** [aleung/jekyll-swagger-ui#1]
Hello @aleung . Thank you for this amazing guide!
By following this, I am getting this error

```
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'swagger' in docs/api/index.html
```
Is there something that I forgot? Sorry if I sound naive.

**Comment by aleung** [comment]
This project was created 6 year ago. I'm afraid that it doesn't work with newer version of Jekyll.

**Comment by shubhank-saxena** [comment]
Ohh. Once again, thank you!
